version: "3"
services:
  frontend1:
    build: ./frontend
    ports:
      - "80"
  frontend2:
    build: ./frontend
    ports:
      - "80"

  frontend-balancer:
    build: ./frontend-balancer
    links:
      - frontend1
      - frontend2
    ports:
      - "3000:80"

  # database:
  #   build: ./database
  #   environment:
  #     - POSTGRES_PASSWORD=${TWATTER_DB_PW}
  #   ports:
  #     - "5432:5432"
  database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=jizzle"
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - IS_CONTAINER=1
      - TWATTER_DB_HOST=database
      - TWATTER_DB_PW=${TWATTER_DB_PW}
      - TWATTER_GITHUB_CLIENT_SECRET=${TWATTER_GITHUB_CLIENT_SECRET}
      - TWATTER_IMGUR_CLIENT_ID=${TWATTER_IMGUR_CLIENT_ID}
    links:
      - database
      - posts-service
      - charts-service
    ports:
      - "8080:8080"

  # posts
  posts-database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=jizzle"
    ports:
      - "5432"
  posts-service:
    build: ./post-service
    environment:
      - IS_CONTAINER=1
      - TWATTER_DB_HOST=posts-database
    links:
      - posts-database
    ports:
      - "34566"

  # charts
  charts-database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=jizzle"
    ports:
      - "5432"
  charts-service:
    build: ./charts-service
    environment:
      - IS_CONTAINER=1
      - TWATTER_DB_HOST=charts-database
    links:
      - charts-database
    ports:
      - "34567"

  # whiteboard
  whiteboards-database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=jizzle"
    ports:
      - "5432"
  whiteboards-service:
    build: ./whiteboard-service
    environment:
      - IS_CONTAINER=1
    links:
      - whiteboards-database
    ports:
      - "34343:34343"
