version: "3"
services:
  # frontend1:
  #   build: ./frontend
  #   ports:
  #     - "80"
  #   labels:
  #     kompose.image-pull-policy: IfNotPresent
  # frontend2:
  #   build: ./frontend
  #   ports:
  #     - "80"
  #   labels:
  #     kompose.image-pull-policy: IfNotPresent

  # frontend-balancer:
  #   build: ./frontend-balancer
  #   links:
  #     - frontend1
  #     - frontend2
  #   ports:
  #     - "3000:80"
  #   labels:
  #     kompose.service.type: nodeport
  #     kompose.image-pull-policy: IfNotPresent

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    image: localhost:5000/frontend
    labels:
      kompose.service.type: nodeport
      kompose.image-pull-policy: IfNotPresent

  backend-database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jizzle
    ports:
      - 5432:5432
    labels:
      kompose.image-pull-policy: IfNotPresent
  backend:
    build: ./backend
    environment:
      - IS_CONTAINER=1
      - TWATTER_DB_HOST=backend-database
      - TWATTER_DB_PW=jizzle
      - TWATTER_GITHUB_CLIENT_SECRET=${TWATTER_GITHUB_CLIENT_SECRET}
      - TWATTER_IMGUR_CLIENT_ID=${TWATTER_IMGUR_CLIENT_ID}
    links:
      - backend-database
      - posts-service
      - charts-service
    ports:
      - "8080:8080"
    image: localhost:5000/backend
    labels:
      kompose.service.type: nodeport
      kompose.image-pull-policy: IfNotPresent

  # posts
  posts-database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=jizzle"
    ports:
      - "5432"
    labels:
      kompose.image-pull-policy: IfNotPresent
  posts-service:
    build: ./post-service
    environment:
      - IS_CONTAINER=1
      - TWATTER_DB_HOST=posts-database
    links:
      - posts-database
    ports:
      - "34566"
    image: localhost:5000/posts-service
    labels:
      kompose.image-pull-policy: IfNotPresent

  # charts
  charts-database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=jizzle"
    ports:
      - "5432"
    labels:
      kompose.image-pull-policy: IfNotPresent
  charts-service:
    build: ./charts-service
    environment:
      - IS_CONTAINER=1
      - TWATTER_DB_HOST=charts-database
    links:
      - charts-database
    ports:
      - "34567"
    image: localhost:5000/charts-database
    labels:
      kompose.image-pull-policy: IfNotPresent

  # whiteboard
  whiteboards-database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=jizzle"
    ports:
      - "5432"
    labels:
      kompose.image-pull-policy: IfNotPresent
  whiteboards-service:
    build: ./whiteboard-service
    environment:
      - IS_CONTAINER=1
    links:
      - whiteboards-database
    ports:
      - "34343:34343"
    image: localhost:5000/whiteboards-database
    labels:
      kompose.service.type: nodeport
      kompose.image-pull-policy: IfNotPresent
