services:
  frontend1:
    build: ./frontend
  frontend2:
    build: ./frontend

  frontend-balancer:
    build: ./balancer
    ports:
      - "3000:80"
    links:
      - frontend1
      - frontend2

  backend:
    build: ./backend
    environment:
      - TWATTER_GITHUB_CLIENT_SECRET=${TWATTER_GITHUB_CLIENT_SECRET}
      - TWATTER_DB_PW=${TWATTER_DB_PW}
      - TWATTER_DB_HOST=${TWATTER_DB_HOST}
      - TWATTER_IMGUR_CLIENT_ID=${TWATTER_IMGUR_CLIENT_ID}
    ports:
      - "8080:8080"
    links:
      - database

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${TWATTER_DB_PW}
    ports:
      - "5432:5432"

