# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gateway test, build & package

on: [push, pull_request]

jobs:
  test-build-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Change wrapper permissions
      working-directory: backend
      run: chmod +x ./gradlew
      
    - name: Test
      working-directory: backend
      run: ./gradlew test
      
    - name: Build
      working-directory: backend
      run: ./gradlew build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        title: Release ${{ github.run_number }}
        automatic_release_tag: latest
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
            backend/build/libs/Twatter-0.0.1-SNAPSHOT.jar
